// This file is automatically generated by Monicon. Do not edit this file directly.
module.exports = {
  "ph:user": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M230.92 212c-15.23-26.33-38.7-45.21-66.09-54.16a72 72 0 1 0-73.66 0c-27.39 8.94-50.86 27.82-66.09 54.16a8 8 0 1 0 13.85 8c18.84-32.56 52.14-52 89.07-52s70.23 19.44 89.07 52a8 8 0 1 0 13.85-8M72 96a56 56 0 1 1 56 56a56.06 56.06 0 0 1-56-56\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:user-fill": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M230.93 220a8 8 0 0 1-6.93 4H32a8 8 0 0 1-6.92-12c15.23-26.33 38.7-45.21 66.09-54.16a72 72 0 1 1 73.66 0c27.39 8.95 50.86 27.83 66.09 54.16a8 8 0 0 1 .01 8\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:presentation": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M216 40h-80V24a8 8 0 0 0-16 0v16H40a16 16 0 0 0-16 16v120a16 16 0 0 0 16 16h39.36l-21.61 27a8 8 0 0 0 12.5 10l29.59-37h56.32l29.59 37a8 8 0 1 0 12.5-10l-21.61-27H216a16 16 0 0 0 16-16V56a16 16 0 0 0-16-16m0 136H40V56h176z\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:presentation-fill": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M216 40h-80V24a8 8 0 0 0-16 0v16H40a16 16 0 0 0-16 16v120a16 16 0 0 0 16 16h39.36l-21.61 27a8 8 0 0 0 12.5 10l29.59-37h56.32l29.59 37a8 8 0 1 0 12.5-10l-21.61-27H216a16 16 0 0 0 16-16V56a16 16 0 0 0-16-16\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:calendar-check": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M208 32h-24v-8a8 8 0 0 0-16 0v8H88v-8a8 8 0 0 0-16 0v8H48a16 16 0 0 0-16 16v160a16 16 0 0 0 16 16h160a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16M72 48v8a8 8 0 0 0 16 0v-8h80v8a8 8 0 0 0 16 0v-8h24v32H48V48Zm136 160H48V96h160zm-38.34-85.66a8 8 0 0 1 0 11.32l-48 48a8 8 0 0 1-11.32 0l-24-24a8 8 0 0 1 11.32-11.32L116 164.69l42.34-42.35a8 8 0 0 1 11.32 0\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:calendar-check-fill": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M208 32h-24v-8a8 8 0 0 0-16 0v8H88v-8a8 8 0 0 0-16 0v8H48a16 16 0 0 0-16 16v160a16 16 0 0 0 16 16h160a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16m-38.34 101.66l-48 48a8 8 0 0 1-11.32 0l-24-24a8 8 0 0 1 11.32-11.32L116 164.69l42.34-42.35a8 8 0 0 1 11.32 11.32M48 80V48h24v8a8 8 0 0 0 16 0v-8h80v8a8 8 0 0 0 16 0v-8h24v32Z\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:calendar": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M208 32h-24v-8a8 8 0 0 0-16 0v8H88v-8a8 8 0 0 0-16 0v8H48a16 16 0 0 0-16 16v160a16 16 0 0 0 16 16h160a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16M72 48v8a8 8 0 0 0 16 0v-8h80v8a8 8 0 0 0 16 0v-8h24v32H48V48Zm136 160H48V96h160zm-96-88v64a8 8 0 0 1-16 0v-51.06l-4.42 2.22a8 8 0 0 1-7.16-14.32l16-8A8 8 0 0 1 112 120m59.16 30.45L152 176h16a8 8 0 0 1 0 16h-32a8 8 0 0 1-6.4-12.8l28.78-38.37a8 8 0 1 0-13.31-8.83a8 8 0 1 1-13.85-8A24 24 0 0 1 176 136a23.76 23.76 0 0 1-4.84 14.45\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:plus": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M224 128a8 8 0 0 1-8 8h-80v80a8 8 0 0 1-16 0v-80H40a8 8 0 0 1 0-16h80V40a8 8 0 0 1 16 0v80h80a8 8 0 0 1 8 8\"/></svg>",
    "width": 16,
    "height": 16
  },
  "arcticons:robotfindskitten-alt": {
    "svg": "<svg viewBox=\"0 0 48 48\" width=\"1em\" height=\"1em\" ><path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M22.83 21.358a1.386 1.386 0 0 0-1.076 2.26l2.222 2.609l2.2-2.583l.01-.012l.012-.014a1.387 1.387 0 1 0-2.222-1.653a1.38 1.38 0 0 0-1.145-.607zm-12.722-3.897c3.095 0 5.604 2.475 5.604 5.528v.79H4.505v-.79c0-3.053 2.509-5.528 5.604-5.528zm-4.839-.826l1.592 1.849m8.086-1.849l-1.592 1.849\"/><g fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12.657\" cy=\"21.23\" r=\"1.02\"/><circle cx=\"7.559\" cy=\"21.23\" r=\"1.02\"/><circle cx=\"39.167\" cy=\"24.795\" r=\"1.02\"/><circle cx=\"34.069\" cy=\"24.795\" r=\"1.02\"/><path d=\"m31.01 16.638l4.078 5.098h3.06l4.077-5.098v14.275H31.01z\"/></g><path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M29.735 28.873h2.549m-2.549-1.529h2.549m8.667 1.529H43.5m-2.549-1.529H43.5m-6.882 1.019v-1.332m0 1.332l-.805.998m-.361-1.73l1.166.732m0 0l.804.998m.361-1.73l-1.165.732M4.5 23.774h11.216v5.608H4.5z\"/><circle cx=\"7.608\" cy=\"30.615\" r=\".75\" fill=\"currentColor\"/><circle cx=\"12.608\" cy=\"30.615\" r=\".75\" fill=\"currentColor\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:caret-right": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"m181.66 133.66l-80 80a8 8 0 0 1-11.32-11.32L164.69 128L90.34 53.66a8 8 0 0 1 11.32-11.32l80 80a8 8 0 0 1 0 11.32\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:caret-left": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M165.66 202.34a8 8 0 0 1-11.32 11.32l-80-80a8 8 0 0 1 0-11.32l80-80a8 8 0 0 1 11.32 11.32L91.31 128Z\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:microphone": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M128 176a48.05 48.05 0 0 0 48-48V64a48 48 0 0 0-96 0v64a48.05 48.05 0 0 0 48 48M96 64a32 32 0 0 1 64 0v64a32 32 0 0 1-64 0Zm40 143.6V240a8 8 0 0 1-16 0v-32.4A80.11 80.11 0 0 1 48 128a8 8 0 0 1 16 0a64 64 0 0 0 128 0a8 8 0 0 1 16 0a80.11 80.11 0 0 1-72 79.6\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:stop-fill": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M216 56v144a16 16 0 0 1-16 16H56a16 16 0 0 1-16-16V56a16 16 0 0 1 16-16h144a16 16 0 0 1 16 16\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:upload": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M240 136v64a16 16 0 0 1-16 16H32a16 16 0 0 1-16-16v-64a16 16 0 0 1 16-16h48a8 8 0 0 1 0 16H32v64h192v-64h-48a8 8 0 0 1 0-16h48a16 16 0 0 1 16 16M85.66 77.66L120 43.31V128a8 8 0 0 0 16 0V43.31l34.34 34.35a8 8 0 0 0 11.32-11.32l-48-48a8 8 0 0 0-11.32 0l-48 48a8 8 0 0 0 11.32 11.32M200 168a12 12 0 1 0-12 12a12 12 0 0 0 12-12\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:waveform": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M56 96v64a8 8 0 0 1-16 0V96a8 8 0 0 1 16 0m32-72a8 8 0 0 0-8 8v192a8 8 0 0 0 16 0V32a8 8 0 0 0-8-8m40 32a8 8 0 0 0-8 8v128a8 8 0 0 0 16 0V64a8 8 0 0 0-8-8m40 32a8 8 0 0 0-8 8v64a8 8 0 0 0 16 0V96a8 8 0 0 0-8-8m40-16a8 8 0 0 0-8 8v96a8 8 0 0 0 16 0V80a8 8 0 0 0-8-8\"/></svg>",
    "width": 16,
    "height": 16
  },
  "ph:github-logo-fill": {
    "svg": "<svg viewBox=\"0 0 256 256\" width=\"1em\" height=\"1em\" ><path fill=\"currentColor\" d=\"M216 104v8a56.06 56.06 0 0 1-48.44 55.47A39.8 39.8 0 0 1 176 192v40a8 8 0 0 1-8 8h-64a8 8 0 0 1-8-8v-16H72a40 40 0 0 1-40-40a24 24 0 0 0-24-24a8 8 0 0 1 0-16a40 40 0 0 1 40 40a24 24 0 0 0 24 24h24v-8a39.8 39.8 0 0 1 8.44-24.53A56.06 56.06 0 0 1 56 112v-8a58.14 58.14 0 0 1 7.69-28.32A59.78 59.78 0 0 1 69.07 28A8 8 0 0 1 76 24a59.75 59.75 0 0 1 48 24h24a59.75 59.75 0 0 1 48-24a8 8 0 0 1 6.93 4a59.74 59.74 0 0 1 5.37 47.68A58 58 0 0 1 216 104\"/></svg>",
    "width": 16,
    "height": 16
  }
};