// This file is automatically generated by Monicon. Do not edit this file directly.
import "@monicon/icon-loader";

declare module "@monicon/icon-loader" {
  export type MoniconIconName = 
	| "ph:user"
	| "ph:user-fill"
	| "ph:presentation"
	| "ph:presentation-fill"
	| "ph:calendar-check"
	| "ph:calendar-check-fill"
	| "ph:calendar"
	| "ph:plus"
	| "ph:arcticons:robotfindskitten-alt"
	| "ph:caret-right"
	| "ph:caret-left"
	| "ph:microphone"
	| "ph:stop-fill"
	| "ph:upload"
	| "ph:waveform";

  export type MoniconProps = {
    /**
     * The name of the icon to render.
     *
     * @example "mdi:home"
     *
     * For TypeScript users, you must check below for more information.
     *
     * @link https://monicon-docs.vercel.app/troubleshooting/typescript
     */
    name: MoniconIconName;
    /**
     * The size of the icon.
     *
     * @default collection's view box size
     */
    size?: number;
    /**
     * The color of the icon.
     *
     * @default "currentColor"
     */
    color?: string;
    /**
     * The stroke width of the icon. This feature is only available for limited icon collections.
     */
    strokeWidth?: number;
  };
}
